# Generated by Django 5.2.9 on 2025-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
